# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://eeznivx.github.io"
baseurl: "/mc.biji.social"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2023
siteFooterlink: /about
showinSearchEngines: true
googleAnalyticsID: G-EMTZ5L1B7W


# Set basic server info
serverName: KEJUTOWN SMP
serverDescription: A Minecraft server where we have lots of fun!
serverIP: play.biji.social:25565
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.biji.social
discordServerID: 229541910719496192
discordChannelID: 552167484459843605


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
